baseURL = "https://toanloi2569.github.io/"
languageCode = "en"
title = "My Knowledge Notes"
defaultContentLanguage = "en"
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 10

[params]
  description = "This is my Personal Blog, sharing knowledge and experience."
  keywords = ["blog", "hugo", "loveit", "personal notes"]
  defaultTheme = "auto"
  dateFormat = "02 Jan 2006"

  [params.author]
    name = "ToanLoi2569"
    email = ""

  [params.footer]
    enable = true
    hugo = true
    since = 2024
    custom = ""

  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      title = "Hi, I'm ToanLoi2569"
      subtitle = "Sharing knowledge and personal experience"
      typeit = false
      social = true

    [params.home.posts]
      enable = true
      paginate = 6

  [params.page]
    readingTime = true
    linkToMarkdown = true

    [params.page.share]
      enable = true

  [params.page.comment]
    enable = false

[params.social]
  GitHub = "https://github.com/your-handle"
  LinkedIn = "https://www.linkedin.com/in/your-handle"
  Twitter = ""

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNos = true
    noClasses = false
    style = "dracula"

[outputs]
  home = ["HTML", "RSS"]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.119.0"
  [[module.imports]]
    path = "github.com/dillonzq/LoveIt"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
